storage:
    type: memory
listen-address: :8081
auth-username: admin
auth-password: password
location: 'http://localhost:8081'
private-key: 8PjzjakvIlh3BVFKe8axinRDutF6EDIfjtuf4+JaNow=
public-key: CIdWcEUN+0OZnKW9KwruRQnQDY/qqzVdD30CijwiWCk=
access-log: access.log
max-mgo-sessions: 300
request-timeout: 2s
private-addr: localhost
admin-agent-public-key: iKp24EL2Aj9MQfRkpwzp7rz7Zf3QZsEzWGpoWT3OK2w=
identity-providers:
- type: static
  name: static
  description: Default identity provider
  users:
    user1:
      name: User One
      email: user1@example.com
      password: password1
      groups:
       - group1
       - group3
    user2:
      name: User Two
      email: user2@example.com
      password: password2
      groups:
       - group2
       - group3
- type: static
  name: static-domain
  domain: domain
  description: Identity provider @domain
  users:
    user1:
      name: User One
      email: user1@example.com
      password: password3
      groups:
       - group1
       - group3
    user2:
      name: User Two
      email: user2@example.com
      password: password4
      groups:
       - group2
       - group3
enable-email-login: true
